name = "bajipoint"
main = "src/index.js"
compatibility_date = "2025-07-13"
workers_dev = true
compatibility_flags = ["nodejs_compat"]
type = "module"

[vars]
MERCHANT_CODE = "SKU20241106070658"
MERCHANT_API = "BLb0eIOjb8ApJhbdMtD56g%3D%3D"
SECRET_KEY = "NGixn2NDe0G0ACaMHaT1URpR19nEqmQ4Rd0ZkylZUds%3D"
PAYOUT_CODE = "BAJI937W"
